// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/contacts.proto

package com.jiangew.protobuf.contacts;

public final class ContactsProto {
  private ContactsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Constacts_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Constacts_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Constacts_Person_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Constacts_Person_PhoneNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Constacts_Contacts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Constacts_Contacts_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035src/main/proto/contacts.proto\022\tConstac" +
      "ts\"\327\001\n\006Person\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022" +
      "\r\n\005email\030\003 \001(\t\022-\n\006phones\030\004 \003(\0132\035.Constac" +
      "ts.Person.PhoneNumber\032H\n\013PhoneNumber\022\016\n\006" +
      "number\030\001 \001(\t\022)\n\004type\030\002 \001(\0162\033.Constacts.P" +
      "erson.PhoneType\"+\n\tPhoneType\022\n\n\006MOBILE\020\000" +
      "\022\010\n\004HOME\020\001\022\010\n\004WORK\020\002\"-\n\010Contacts\022!\n\006peop" +
      "le\030\001 \003(\0132\021.Constacts.PersonB0\n\035com.jiang" +
      "ew.protobuf.contactsB\rContactsProtoP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Constacts_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Constacts_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Constacts_Person_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Phones", });
    internal_static_Constacts_Person_PhoneNumber_descriptor =
      internal_static_Constacts_Person_descriptor.getNestedTypes().get(0);
    internal_static_Constacts_Person_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Constacts_Person_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
    internal_static_Constacts_Contacts_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Constacts_Contacts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Constacts_Contacts_descriptor,
        new java.lang.String[] { "People", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
