// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/contacts.proto

package com.jiangew.protobuf.contacts;

public interface ContactsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Constacts.Contacts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Constacts.Person people = 1;</code>
   */
  java.util.List<com.jiangew.protobuf.contacts.Person> 
      getPeopleList();
  /**
   * <code>repeated .Constacts.Person people = 1;</code>
   */
  com.jiangew.protobuf.contacts.Person getPeople(int index);
  /**
   * <code>repeated .Constacts.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .Constacts.Person people = 1;</code>
   */
  java.util.List<? extends com.jiangew.protobuf.contacts.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .Constacts.Person people = 1;</code>
   */
  com.jiangew.protobuf.contacts.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
