// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/contacts.proto

package com.jiangew.protobuf.contacts;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Constacts.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 id = 2;</code>
   */
  int getId();

  /**
   * <code>string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated .Constacts.Person.PhoneNumber phones = 4;</code>
   */
  java.util.List<com.jiangew.protobuf.contacts.Person.PhoneNumber> 
      getPhonesList();
  /**
   * <code>repeated .Constacts.Person.PhoneNumber phones = 4;</code>
   */
  com.jiangew.protobuf.contacts.Person.PhoneNumber getPhones(int index);
  /**
   * <code>repeated .Constacts.Person.PhoneNumber phones = 4;</code>
   */
  int getPhonesCount();
  /**
   * <code>repeated .Constacts.Person.PhoneNumber phones = 4;</code>
   */
  java.util.List<? extends com.jiangew.protobuf.contacts.Person.PhoneNumberOrBuilder> 
      getPhonesOrBuilderList();
  /**
   * <code>repeated .Constacts.Person.PhoneNumber phones = 4;</code>
   */
  com.jiangew.protobuf.contacts.Person.PhoneNumberOrBuilder getPhonesOrBuilder(
      int index);
}
